### ISSUE TITLE
Auto Terms is buggy with "Existing Content"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1002]
It's possible to run this "Existing Content" option multiple times and keep getting the same result. If you keep running it, the result will always be the same number and the terms won't actually be added.

We should be showing the number of NEW terms added.

<img width="933" alt="Screen Shot 2021-10-19 at 4 54 28 PM" src="https://user-images.githubusercontent.com/3868028/137989261-b075465c-39ef-4aee-a2a4-ea811d73a601.png">

**Comment by olatechpro** [comment]
@stevejburge, that's because we're running same action every time.

That is, scan every post and add terms and if no post is added since last run, it's going to always scan every post.

That doesn't mean it's a bug, it's doing exactly what's meant to do which is to scan all posts, get all terms that match and add to selected posts. 

So, it run 100th of time, it's still going to be same result since there's no addition of post or terms. 

If you feel it should work otherwise, perhaps, you can share your view while putting into consideration that terms and post can change too.
