### ISSUE TITLE
"Show post counts" feature

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1110]
The default "Categories" widget / block has a "Show post counts" feature
<img width="1159" alt="Screen Shot 2021-11-29 at 12 58 42 PM" src="https://user-images.githubusercontent.com/3868028/143919175-18b7d5c4-daf6-4152-8f39-b9a539beaa1a.png">

We should make that available under "Display Format"

<img width="772" alt="Screen Shot 2021-11-29 at 12 59 39 PM" src="https://user-images.githubusercontent.com/3868028/143919292-5feea956-23fc-49b8-84b1-9dfb5887e1a9.png">

**Comment by ojopaul** [comment]
@stevejburge, while working on this feature, i noticed the output use a template `"<a href="%tag_link%" id="tag-link-%tag_id%" class="st-tags t%tag_scale%" title="%tag_count% topics" %tag_rel% style="%tag_size% %tag_color%">%tag_name%</a>"` and part of the option, there's `%tag_count%` which shows if user feel like having count in bracket, they can simply use  `%tag_name% (%tag_count%)` in the format.

So, do we really need this feature ? The reason i asked is because while working on it, i reliazed the only way to show the count is replacing auto `%tag_name%` with `%tag_name% (%tag_count%)` since we're not generating the link but using user template from settings and this means it may affect every places where `%tag_name%` is used in the template which may lead to an unwanted result since the `%tag_name%` may be used in even parameters where user may not be willing to display count ?

Should i go ahead still despite the possible issues ?

**Comment by stevejburge** [comment]
@ojopaul Excellent point

Let's close in favor of https://github.com/TaxoPress/TaxoPress/issues/1121

Let's bring in those tags into the TaxoPress admin area so it's easier for users to find and implement
