### ISSUE TITLE
Issue with "Automatic terms suggestions" and other taxonomies

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1175]
This does not seem to work with Categories and other taxonomies. It will always show only terms

![Screen Shot 2022-01-12 at 11 22 21 AM](https://user-images.githubusercontent.com/3868028/149180010-2d62a9a2-91e7-4ff9-b2a3-fd81eff7d1e9.png)

**Comment by stevejburge** [comment]
This is what we get with WooCommerce and product terms:
![Screen Shot 2022-01-12 at 11 28 06 AM](https://user-images.githubusercontent.com/3868028/149181044-c74af17b-0b6f-421f-a8ab-a875933c2a5a.png)

**Comment by ojopaul** [comment]
@stevejburge the feature rely on "post_title" and "post_content" to suggest term. If the contents doesn't exist or doesn't match terms, there won't be suggestion.

Now, if we're adding support for a specific plugin and mode of saving that(in post_title and post_content) are not in use, we can add whatever they use instead of the field for support.

Will test woocommerce product and it term now to understand what the issue is.

**Comment by ojopaul** [comment]
Hi @stevejburge , in my test, i added a product with post title and content and after that, i created an auto term selecting product category and product post type and after publishing post, the posts was auto termed successfully.

So, can you explain the issue you're facing so i can try using similar method ?

Also, it's good to note products category is not same as category(wordpress category)

**Comment by ojopaul** [comment]
@stevejburge , have you been able to confirm this issue ?

**Comment by stevejburge** [comment]
@ojopaul All good now. I think this was fixed in 3.4.5
