### ISSUE TITLE
Add a Log for Auto Terms

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1243]
Can we build on the feedback inside "Existing Content"?
![Screen Shot 2022-02-14 at 1 17 26 PM](https://user-images.githubusercontent.com/3868028/153922790-78ee97cd-34a6-4bf6-9e1e-942e754e281b.png)

Can we turn this into a log so people can see what has changed? Would it make sense to add a "Log" tab under "Existing Content" and "Schedule"?

![Screen Shot 2022-02-14 at 1 00 48 PM](https://user-images.githubusercontent.com/3868028/153922891-28019532-75c8-4f9f-9f13-47861d3ec519.png)

**Comment by stevejburge** [comment]
One user suggested a log that looks like this:
![image](https://user-images.githubusercontent.com/3868028/154361379-ffbff99e-d89c-4956-8ee2-d61c6099bc8e.png)

**Comment by ojopaul** [comment]
1.) @stevejburge do you want this log to be for every post we check or only those we added terms to ?

2.) 

> "Would it make sense to add a "Log" tab `under "Existing Content" and "Schedule"`?"

Do you mean we should add a single log tab or different logs for existing content and schedule, i'm trying to understand the term  "Log" tab `under "Existing Content" and "Schedule"` so i can do exactly what you want ?

**Comment by stevejburge** [comment]
@ojopaul That image was an idea from a customer.

Maybe he want to see if a schedule failed

**Comment by ojopaul** [comment]
On the failing schedule or not, i still doesn't understand how that'll work since we're not a cron manager plugin, our implementation is to add the cron to wordpress cron schedule and when the cron run, our code run auto terms to look for posts that needed to be auto terms. So, failed or not doesn't come to terms in this since we only get response when our code run and not managing the cron but if what you're requesting is a cron manager, maybe you can signify properly even though the idea doesn't seems to align with the plugin.

On the log tab, you still haven't answered my question on exactly what we're logging.

Is it all posts we checked like we currently have on auto term existing terms either. So, we log everything either we add terms or not ? @stevejburge

**Comment by stevejburge** [comment]
Hi @ojopaul 

OK, good questions. I guess the customers want an answer to this question:

> I click "Add Auto Terms to Existing Content" or I set an "Hourly" schedule. What exactly happened? What terms were added to what posts?

**Comment by ojopaul** [comment]
Okay, now for confirmation, when user click auto terms, we checked posts and only add terms to those that match criterias.

Now, do you want us to log every post we checked or only those we add terms to ?

**Comment by stevejburge** [comment]
Thanks. I think this will clear up some mystery around Auto Terms.

At the moment, we process the Auto Terms and then wonder .... "what happened?"
