### ISSUE TITLE
Simpler message in Logs

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1267]
We can just say "No matching terms found"

![Screen Shot 2022-02-22 at 9 00 51 AM](https://user-images.githubusercontent.com/3868028/155147548-3e0a4618-73f8-409a-8af6-545e53f50b92.png)

**Comment by ojopaul** [comment]
@stevejburge , we currently have the following messages depending on the reason incase you want to modify some:

- Auto terms settings does not exist.
- Auto terms settings configured to skip post with terms.
- Post content is empty.
- Terms added successfully.
- No matching terms for auto terms settings options and the post content.

**Comment by stevejburge** [comment]
Thanks. What does the first one signify? "Auto terms settings does not exist."

**Comment by ojopaul** [comment]
Well, it's a situation that's not supposed to happen but in coding, check should always be done for everything.

It imply the request where auto term settings does not exist like probably deleted which doesn't make sense because if it's deleted, it won't make the request but the check is necessary just incase external plugin is making request to add data to our logs using our method without provided a valid auto term settings ID. @stevejburge

**Comment by ojopaul** [comment]
All right
