### ISSUE TITLE
New filters for Logs

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1291]
Could add new filters in addition to "Source"?

- Post type
- Taxonomy
- Status message
- Settings

![Screen Shot 2022-03-04 at 4 02 08 PM](https://user-images.githubusercontent.com/3868028/156841065-9c902170-f9fb-448a-b03d-7f19dc2207e6.png)

**Comment by ojopaul** [comment]
@stevejburge , it's impossible for everything to stay in one line due to introduction of new buttons Delete and Disable as well number of auto terms limit input.

So, everything doesn't look good and as a result, will move the filters to new line on it own and not directly in the middle of bulk action and pagination(pagination will show when there are more item) and also limit the space available
