### ISSUE TITLE
Layout changes for Logs

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1297]
These changes may give us more space on the screen:

![Screen Shot 2022-03-08 at 7 39 21 AM](https://user-images.githubusercontent.com/3868028/157240486-cb1fb433-8a47-4d56-bd80-4ac1f77d6695.png)

**Comment by ojopaul** [comment]
@stevejburge , it's impossible for limit to stay besides the buttons which are inline element due to it label been block element(need to stay on the top of the field).

So, i can either move limit to filter area or alternatively, we remove limit label and change the limit update button to something like "Update number of auto terms logs" or we can let the label text stay beside the input itself.

What should we go for here ?

**Comment by ojopaul** [comment]
This is what i mean by been besides:

![besides](https://user-images.githubusercontent.com/92122385/157272792-a928e93d-1fcb-4b0f-a1bb-377ae2458a20.jpg)

**Comment by stevejburge** [comment]
@ojopaul OK, understood. Maybe "Limit the number of logs" can go above the search box?

Everything under the search box can go on one line?

**Comment by ojopaul** [comment]
Okay, for everything to stay in one line, we'll need to reduce the dropdown width. So, will do that.
