### ISSUE TITLE
Is it possible to make our shortcode or widgets work with WPML?

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1315]
I can set up a test site to help with this.

Details here:
https://wpml.org/documentation/support/achieving-wpml-compatibility-for-your-themes-and-plugins/#8

**Comment by ojopaul** [comment]
@stevejburge 
The following widget already support widget translation as it title passed through widget_title filter:
- 'Tag Cloud (TaxoPress Legacy)

The other widgets are only an instance that allow user to select shortcode and use as widget and as a result, we didn't provide widget title option other than allowing user to select the shortcode they want to render.

In view of the above statement, i don't think there's any changes needed to made in this direction.

**Comment by stevejburge** [comment]
@ojopaul I think what may be needed is another filter inside these settings:

- Terms Display
- Terms for Related Posts
- Related Posts etc

This would be a language filter. So for example, "Terms Display" would have an option to only show Spanish terms, or French terms.

This may be a big task, because WPML isn't the only option.

**Comment by ojopaul** [comment]
Okay, maybe you should setup a WPML set to enable me go through it.

On `"This may be a big task, because WPML isn't the only option."`, can you list every options we're providing support for since each plugin implementation will be different and can't be the same. So, each extension will be tailored to each plugin we're adding support for as anything out of native WordPress way will definitely have different mode of implementation. @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Thanks. I'll set up a test site for us. We'll look at some simple language support and maybe WPML too

**Comment by ojopaul** [comment]
@stevejburge let me know when we have update on this

**Comment by stevejburge** [comment]
@ojopaul Let's pause this. I spent time investigating and there's too much to do
