### ISSUE TITLE
One set of logs reports for a large, slow site

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1322]
@ojopaul We have one customer with 200,000 posts. Auto Terms was crashing their server. Do the attached logs help at all?

> We had the settings for Use existing terms, 40 second delay , 20 in batch.
> 
> I turned logs off. Max 1 month
> 
> It seems to go through all the files constantly - not just 1 month.
> 
> Once I activate the plug within an hour it brings our SQL traffic up tremendously.
> 
> When I activated the plug the load for our entire (very large server) went from 5-10 to sometimes more than 100 . At 70 it will bring down all our websites.
> 
> The SQL processes also went up to 10,000 and more making all our websites time out.

[Tag-20c886c834e62c08ea859854bb098caa.pdf](https://github.com/TaxoPress/TaxoPress/files/8248895/Tag-20c886c834e62c08ea859854bb098caa.pdf)

**Comment by ojopaul** [comment]
@stevejburge i've seen where the problem is on this. 

After this update, using https://github.com/TaxoPress/TaxoPress/issues/1314 with time limit will fix issues with last site.

For example, when a site set limit to 30 posts with option to only run auto term schedule for posts once, that'll prevent running one set of post over and over again as well limit the number of query.

I'm sorry for not foreseeing this ahead.
