### ISSUE TITLE
user unable to edit/type in new values in text field under "Use only some terms in the selected taxonomy."

### ISSUE THREAD

**Issue by AlesyaBreenkova** [TaxoPress/TaxoPress#1333]
1. Go to TaxoPress > Auto Terms > "Manage Auto Terms".
2. On the Auto Terms List page click Edit for any of the items (example URL: /wp-admin/admin.php?page=st_autoterms&add=new_item&action=edit&taxopress_autoterms=8 )
3. On the "Manage Auto Terms" page click the "Sources" tab.
4. Select the "Use only some terms in the selected taxonomy." checkbox.
5. If the text field under the checkbox is empty, select a few tags from the drop-down list and click "Save Auto Terms".
6. Set the focus on the text field again and start typing. The system won't allow the user to type in anything.

As a result, the user is unable to search within the tag list. 

![image](https://user-images.githubusercontent.com/31319775/159189486-18916db6-6468-4d83-92d9-8f35f88110cb.png)

**Comment by ojopaul** [comment]
@stevejburge @AlesyaBreenkova I tested this feature and it's working as designed. So, i'm not sure what the problem is or able to recreate inability to type in the search input even after select or before adding terms in the input as i'm still able to type.

Side note, there's be need to place cursor by tapping the text input field just incase the report is due to an expectation of been able to continue typing after scrolling the result as search is on input text field and not select option.
