### ISSUE TITLE
Log limit not working correctly

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1349]
I'm not sure the Log limit is working correctly. This is from TaxoPress.com:
<img width="490" alt="Screen Shot 2022-03-27 at 4 12 59 PM" src="https://user-images.githubusercontent.com/3868028/160299191-18084084-6028-4a2f-b7a8-4f33473fb58b.png">

**Comment by ojopaul** [comment]
@stevejburge  could it be that the logs were already there before you set 500 limits?

If so, the list won't be cut down to 500 from the current over 2k as we check if limit is exceeded and delete the first item which should work unless the exceed is above the limit you set.

The reason is because i was trying to consider heavy load on having to run that limit check and then delete all time since auto terms limit run every time.

Here is how it should work, let assume they set the log limit to 1000+, we'll first retrieve the first 1000+ in one database call then make another database call to delete others that doesn't belong to the first 1000+ ID. I believe this will be too heavy to be running every time auto terms log run and as a result, i only check the count and if it greater than the limit, delete the first entry in the list and this will always work for all data before the update but if we see this is an issue, maybe we should introduce date limit instead? The query to delete all logs after specific date is more okay than querying about 1000+ posts every time a post operation happen or even larger number since user have the freedom to enter the limit number.


But current implementation works if auto terms logs hasn't exceed the log limit the user is updating it too and if not, i can test again on this condition but if user is updating to limit that's lower than what's currently in logs, of course, the log won't exceed what's currently in the lists but it won't be cut down to the number entered before due to reason above. So, if a lower log is needed, maybe deleting those that were there before setting the limit and watch new ones.

Let me know whatever your input is and if you still need us to proceed with this?

**Comment by stevejburge** [comment]
Good thinking @ojopaul. I can confirm this work as you designed it
