### ISSUE TITLE
Allow custom auto terms schedule options

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1551]
Can we allow users to choose more schedule options than just Hourly or Daily? One user was requesting the ability to choose a number of minutes.

https://taxopress.com/add-terms-imported-wordpress-posts/

**Comment by ojopaul** [comment]
@stevejburge I've checked every options but unfortunately, I don't see any safe way to allow dynamic options for cron.

That's because https://developer.wordpress.org/reference/functions/wp_schedule_event/ require a valid callback and for us to create a callback function, that shows we already know what to expect.

The only other way to extend this feature is to add more schedule options if we see the need.

For example, we can add:

15 Minutes Interval
30 Minutes Interval
2 Hours Interval
6 Hours Interval
1 Week Interval
1 Month Interval


but the idea of ability ti choose a number of minutes won't work

**Comment by ojopaul** [comment]
@stevejburge Check my comment here

**Comment by stevejburge** [comment]
@ojopaul Sure, let's leave this for now. We can come back to this later with bigger plans
