### ISSUE TITLE
Clarify the attachment options for Auto Links

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1623]
These two boxes are confusing:
<img width="1058" alt="Screenshot 2023-04-14 at 11 31 56 AM" src="https://user-images.githubusercontent.com/3868028/232089344-f487868c-e9af-4f7d-b225-570bdf40253a.png">

Can we provide one box?
- Default: Only add Auto Links for terms that are attached to the post.
- Other option: Only add Auto Links for terms that are not attached to the post.
- Other option: Add Auto Links for all terms.

**Comment by ojopaul** [comment]
@stevejburge I'm adding this comment here as this issue is added as part of https://github.com/TaxoPress/TaxoPress/issues/1656

I think there's some misunderstanding or wrong label as those two options are not same thing going by the source code.

1. **Add links for unattached terms:** _By default, TaxoPress will only add Auto Links for terms that are attached to the post. If this box is checked, TaxoPress will add links for all terms._
So, this only determine the source of auto links terms
- If the option is enabled, autolink terms will be from all the selected taxonomy terms
- If the option is disabled, autolink terms will be from current post

2. **Don't add links for attached terms:** _Don't add Auto Links if the term is already attached to the post._
- If the option is enabled, autolink will not be added for linked that are already added to the post as terms
- If the option is disabled, autolink will be added even if term is added/assigned to the post

I tried to explain based on the source code but the thing is, both option are not same, neither are they word and opposite as they're used in different action.

**Comment by stevejburge** [comment]
Thanks @ojopaul 

I think is confusing and perhaps can be contradictory. It seems like you can choose options for 1 and 2 that will be the opposite of each other?

Could we combine these into one in the code?

**Comment by ojopaul** [comment]
You still didn't understand it, they're not opposite of each other as they're used in different location as explained.

Literally, the code cannot be combined, but we can remove one if we feel they're the same but checking the source code, they're not.

So, I'll scrap one and maybe you'll understand better during test if something is not working

@stevejburge

**Comment by stevejburge** [comment]
@ojopaul OK, how about this?

Title: Add links for all terms
Description: By default, TaxoPress will add links for all terms. If this box is unchecked, Auto Links will only add links for terms that are attached to the post. 

This would mean changing the default for this first option
