### ISSUE TITLE
Custom Title for Related Posts

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1629]
> For the names of my various RelatedPosts functions, I use an internal naming convention which is not user-friendly, therefore I don't want to display these names when I display the lists of posts.
> 
> I would like to be able to specify a user-friendly 'display title' that could be shown rather than the internal name.
> 
> For example (see attached screenshot), I would like to display "Stores" as a title rather than the name of the function (i.e. "ABC_Organization_Stores").

![Screenshot-2023-04-16-135758](https://user-images.githubusercontent.com/3868028/232553762-c666669b-b483-40a8-a35c-744e537ce0e9.png)

**Comment by stevejburge** [comment]
One more for this:

> A request to be able to use the %% tags in the header - so it could read ‘More events in TAG NAME’ 

> also worth noting the header for the Related Posts area text box, cuts off at a crazy low character count

**Comment by ojopaul** [comment]
I'm closing this because we'll be implementing addition of 
- "Text to display before related posts" to "Related Posts" which can serve as Custom Title https://github.com/TaxoPress/TaxoPress/issues/1600
- There's an option "Hide title in output ?" which can be used to disable the title from frontend and this way, the original title can be removed from frontend while Text to display before will serves as custom title.
