### ISSUE TITLE
Auto add tags when using clicktag in classic editor

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1654]
This process was confusing to a customer. They added tags, but didn't realize they also had to click the "Add" button.

Can we make this a one-click process? You just click the "Show existing terms" box
![Screenshot 2023-06-02 at 2 09 01 PM](https://github.com/TaxoPress/TaxoPress/assets/3868028/0cb07beb-4546-4d13-92c6-fed90287f02d)

**Comment by ojopaul** [comment]
> This process was confusing to a customer. They added tags, but didn't realize they also had to click the "Add" button.

To be sincere, they don't have to click on "Add" button before publish as that's how Tags works as far as WordPress is concerned.

Even if you search for tag and click it, it'll simply be added to the input and publishing the post will add it even without clicking the "Add".

But due to this request, I'll trigger click on the "Add" so the new Tag is shown in the list instead of the input but there's a con to this which is the fact browser may change focus to the tag input from where user are currently is since the "Add" button is the last triggered input.

@stevejburge
