### ISSUE TITLE
Make Auto Links Exclude terms bigger and Add Autocomplete to the field

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1680]
This was reported by a customer and I can confirm in my testing

- The "Exclude terms from Auto Links" box isn't big enough for a long list
- This feature works inconsistently. Details: https://secure.helpscout.net/conversation/2285272931/200103?folderId=4410097

<img width="1082" alt="Screenshot 2023-06-27 at 8 54 34 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/ac8b07e5-3e12-4b7d-9116-ff6d56d931f2">

**Comment by stevejburge** [comment]
One customer wants us to leave this text box behind in favor of a select list

> As a suggestion: a checkbox selector to unselect terms in the terms list would be great (including a filter for the list based on status). This can be expanded to other criteria for terms that might be applied anywhere else inside of Taxopress and is more user friendly than a text field which can become quite extensive/cluttered when there are many used terms.

I'll open a new issue for the uppercase-lowercase

**Comment by ojopaul** [comment]
@stevejburge select box is not realistic for this field. Existing data will be lost due to it been text that could possibly not match a term/term ID.

If the size is the problem, I'll make this a textarea that can be resized manually and add autocomplete to it if possible since we already open a new issue on term case.

**Comment by stevejburge** [comment]
Thanks @ojopaul. OK, let's do our best then. A larger box and autocomplete will be better
