### ISSUE TITLE
Can we speed up the adding of terms via Suggest Terms?

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1763]
[#post-16942068](https://wordpress.org/support/topic/block-editor-25/

**Comment by ojopaul** [comment]
@stevejburge Adding tags is a process where we make a call to the function to add tags.
On ways to speed up the process? No, I don't see any for now since that's dependent on wordpress API.

However, we can investigate the issue of terms not been added if clicked too fast in Block editor to fix that.

If that's okay, then the issue should be updated to reflect that so as not to give impression of the speed when making changelog based on fixed issue

**Comment by stevejburge** [comment]
@ojopaul OK, let's leave this open for later
