### ISSUE TITLE
Add more information to REST API tab

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1825]
Can we make it easier for users to test and verify that the REST API is working.

For example, can we add links to the REST API output for the taxonomy and a sample term?
<img width="988" alt="Screenshot 2023-09-19 at 1 47 00 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/0c3ccb1f-8f36-4994-8f6d-6afb80b95556">

**Comment by ojopaul** [comment]
@stevejburge  Do you mean we should add a link to the site rest api for the taxonomy?

Something like 
- https://publishpress.com/wp-json/wp/v2/categories for category
- https://publishpress.com/wp-json/wp/v2/tags for tags
- /wp-json/wp/v2/taxonomies/{taxonomy_base_slu} for custom taxonomy

Since that's what shows if it's enabled in rest api or not

**Comment by stevejburge** [comment]
@ojopaul Yes, please. That works. We've run into some issues where users have the REST API blocked.
