### ISSUE TITLE
Merge feature is broken

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1904]
I can confirm this: https://wordpress.org/support/topic/merged-tags-being-deleted-issue/

This will lead to both terms being deleted
<img width="749" alt="Screenshot 2023-10-23 at 9 14 14 AM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/9511cd71-3617-4785-bc10-b2e8dd6e6086">

**Comment by ojopaul** [comment]
Here's how Merge Term works.
Step 1: Merge all Terms in "Term to Merge" to "New Term"
Step 2: Delete Old Term in "Term to Merge" after merging

And in this case, Term A and B.

I think the problem is wrong usage.

If you want to Merge Term A to Term B, it's as simple as providing B in the first box and A in the second box.

The usage is totally wrong even from normal point of view asking a system to merge a Term to its Own whereby the Old Term must be deleted after merging.

So, the term is gone and nothing can be done with it.

All I can do is add an error message in cases like that where Term to Merge To and from is the same thing.

To be sincere, the feature is not broken but usage was wrong. @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Maybe we should update the labels

@ojopaul Maybe 

"This feature will remove existing terms and replace them with new term. Any posts assigned to the old terms will be re-assigned to the new term.

- Term(s) to merge. These terms will be removed. 

- New term name

**Comment by ojopaul** [comment]
Make sense @stevejburge

**Comment by stevejburge** [comment]
@ojopaul Should we also force users to choose an existing term in the second box?

**Comment by ojopaul** [comment]
If you choose the same Term in A and B, it'll still give the same result with the term being deleted. So, it doesn't make any difference

**Comment by stevejburge** [comment]
@ojopaul I created problems this way:

- Choose an existing term in the first box
- Choose a term that does not exist in the second box

**Comment by ojopaul** [comment]
@stevejburge In all the inputs on the screen, we only suggest terms and that doesn't mean any texts can't be added.

So, if you intend to create a problem like the above after the implementation, feel free to cos you'll still be able to do so cos the result will be the same thing :)

In summary, we can add term suggestions but it doesn't stop people from adding text like you did above (If they feel doing so is our problem)

**Comment by stevejburge** [comment]
@ojopaul OK, let's skip that for now and just update the text
