### ISSUE TITLE
Remove TaxoPress AI pro metaboxes in Free version

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1921]
OpenAI and IBM have Pro banners. There's a design issue with them in Safari:
<img width="1183" alt="Screenshot 2023-10-25 at 3 59 05 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/90dbbb6b-df50-46a1-b1ed-429fd07bd3ba">

Dandelion and LSEG don't have banners:
<img width="1192" alt="Screenshot 2023-10-25 at 3 59 58 PM" src="https://github.com/TaxoPress/TaxoPress/assets/3868028/7debf757-d468-4a18-a07b-241ed6c7c9f3">

I'm thinking maybe we just hide these for Free users? No API keys = no box

**Comment by ojopaul** [comment]
@stevejburge 
I believe the reason you see them in the metabox to start with is because you do have an API key for them and probably deactivate Pro version to test free version which doesn't delete the API data saved in Pro version before deactivation.

But since you said they should outrightly be removed, I'll work on that.
