### ISSUE TITLE
WordPress lists fail when content includes "<"

### ISSUE THREAD

**Issue by reekes** [TaxoPress/TaxoPress#1961]
I haven't found any reports of this, but it's 100% happening for me in the most simple example. I haven't found any work around. This only happens when TaxoPress Pro is activated.

## Expected Behavior

Lists should display as expected.

Create a list such as this and confirm this displays in the web page as expected.

This...
```
   List Item 1
   List Item 2
   List Item 3

```
Will render as expected:
-    List Item 1
-    List Item 2
-    List Item 3

Change the content by adding "<"...
```
   List Item 1
   List <Item> 2
   List Item 3

```
This should render as below. NOTE: I had to add backquotes around the angle brackets because GitHub was swallowing`<Item>` !
-    List Item 1
-    List `<Item>` 2
-    List Item 3

## Current Behavior

Change the content to this, adding "<" and ">" around any word... 
```
   List Item 1
   List <Item> 2
   List Item 3

```
Now the content will render as:
-    List Item 1
-    
-    List Item 3
## Possible Solution

Nothing I've tried can workaround this bug.

## Steps to Reproduce (for bugs)

1. Create a list in WordPress Gutenberg
2. Put "<" around any word
3. Render the page at the front end
4. Note the entire line of this list item is missing

## Context

This is a serious bug. It's corrupting pages.

## Your Environment

WordPress 6.4.2
Astra theme 4.5.2
Chrome 119.0.6045.199 (Official Build) (x86_64)
Mac 14.1.2

I disabled ALL plugins and used just WordPress and Taxopress Pro and I can reproduce the problem

**Comment by ojopaul** [comment]
Hi @reekes @stevejburge 
I'm trying to replicate this issue but here's the result in my testing:

Content
![Screenshot Capture - 2024-01-30 - 15-17-11](https://github.com/TaxoPress/TaxoPress/assets/92122385/7969cbe9-ac41-4a0e-80e9-da2a4b42923c)


Display:
![Screenshot Capture - 2024-01-30 - 15-18-07](https://github.com/TaxoPress/TaxoPress/assets/92122385/624a5ee8-0802-42d8-8dbd-67573aad0ff3)


I'm not able to replicate the reported issue, not sure if I'm misunderstanding the content or something else.

Also, it's good to note your browser will read any content inside < and > as a tag and won't render it on display and that's why the < item > is not showing in my case as browser will translate it to html unless you're using reach editor that translate it to &lt ; and &gt ; and in that case, i got the correct output.

Do you mind sharing content screenshot?

**Comment by reekes** [comment]
This has nothing to do with a browser. The problem happens when WordPress renders the HTML (so any browser will fail). The HTML output from WordPress is corrupt.

This does NOT happen if I disable Taxopress. This problem ONLY happens when I enable Taxopress.

This first image shows what I have in the WordPress editor...
![backend-editor1](https://github.com/TaxoPress/TaxoPress/assets/18753948/f6d01742-7c81-41aa-b1e3-d9b6c30b2151)

This is what is rendered by that content in the HTML (looks as expected)...
![html-render1](https://github.com/TaxoPress/TaxoPress/assets/18753948/3a87ea1e-2015-4a7c-b76c-4cd88e1a819d)

This is what I have in the WordPress editor. I've put <> around the word PTU...
![backend-editor2](https://github.com/TaxoPress/TaxoPress/assets/18753948/eb7de2e6-03ba-48a8-bd35-c6b8fcf70691)

The HTML is then rendered as this...
![html-render2](https://github.com/TaxoPress/TaxoPress/assets/18753948/3d7399f5-ff27-4875-83fe-36581fde9040)

As you can see, the entire line has been removed. The raw HTML in the Chrome inspector shows nothing for the entire contents of the `<li>` tag. There's content within the `<li></li>`

Taxopress is swallowing the content when I put "<" or ">" into a list.

This does NOT happen if I disable Taxopress

**Comment by ojopaul** [comment]
@reekes I think you're misunderstanding my response. When i say browser will convert<item> to tag when rendered, I'm refering to my screenshot where that part is missing and that's true. 

The reason you may not know is the fact rich editor convert < to  &lt for you. If you want to confirm, try classic editor in text mode to put raw <item> and you'll see the item will be converted to tag if you inspect element(Not same as the whole line missing).

Now, back to the main issue, I'm not able to replicate this and that's the reason I asked for content as it's possible for Certain special character or html/link combination to cause issue for Autolinks. That's the reason I asked for the content.
But like i said, testing the sample content i pasted in the simplest possible way, I'm not able to replicate this issue and it's almost impossible to fix something you can't replicate when it come to issue like this.

If you were not able to help further on replicating this issue, you can disable Autolink on the affected post as shown in the screenshot below, otherwise, raw html of the content will be helpful

![Screenshot Capture - 2024-02-01 - 09-57-36](https://github.com/TaxoPress/TaxoPress/assets/92122385/e56d6d2e-7648-49ff-896c-2c609da58a7b)

**Comment by reekes** [comment]
Enter this into the WordPress editor. Here I'm showing this in Gutenberg. The problem also happens with the old (classic) editor.

Have "Add links for all terms" enabled in Auto Links.

1. Add a term known to Taxopress
2. Create a list like this in the editor
![Screenshot 2024-02-01 at 5 48 58 AM](https://github.com/TaxoPress/TaxoPress/assets/18753948/fe2b91f0-d5d5-4bb8-8623-e4d01ce52c86)

This is the raw text in HTML

```
<!-- wp:paragraph -->
<p>Taxopress term "storage"</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>List item 1</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List item 2</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List item 3</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
```

This is how the page looks at the front end.
![Screenshot 2024-02-01 at 5 49 43 AM](https://github.com/TaxoPress/TaxoPress/assets/18753948/e5db0283-72ef-40c1-a212-b0c6ae9a882e)

The raw HTML of the front-end page
```
<div class="entry-content clear" ast-blocks-layout="true" itemprop="text">
<p>Taxopress term &ldquo;<a href="https://argonsys.com/tag/storage/" class="st_tag internal_tag " rel="tag" title="Find articles tagged with Storage">storage</a>&rdquo;</p>
<ul>
<li>List item 1</li>
<li>List item 2</li>
<li>List item 3</li>
</ul>
</div><!-- .entry-content .clear -->
```

So far, everything above is working exactly as expected.


**To create the bug...**

Add "<" to one of the items in the list, like this.
![Screenshot 2024-02-01 at 5 51 25 AM](https://github.com/TaxoPress/TaxoPress/assets/18753948/89176317-13e0-4d4d-b598-c85e1d6d331c)

This is now the raw HTML in the editor. This is all working as expected.

```
<!-- wp:paragraph -->
<p>Taxopress term "storage"</p>
<!-- /wp:paragraph -->

<!-- wp:list -->
<ul><!-- wp:list-item -->
<li>List item 1</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List &lt; item 2</li>
<!-- /wp:list-item -->

<!-- wp:list-item -->
<li>List item 3</li>
<!-- /wp:list-item --></ul>
<!-- /wp:list -->
```

This is how the page now looks at the front end. The item has been entirely removed from the list by Taxopress.
![Screenshot 2024-02-01 at 5 53 16 AM](https://github.com/TaxoPress/TaxoPress/assets/18753948/98f3c896-cc00-426a-9fd9-5fdb9a01d3c0)

The raw HTML at the front end is now this, clearly showing the item has been deleted by Taxopress.

```
<div class="entry-content clear" ast-blocks-layout="true" itemprop="text">
<p>Taxopress term &ldquo;<a href="https://argonsys.com/tag/storage/" class="st_tag internal_tag " rel="tag" title="Find articles tagged with Storage">storage</a>&rdquo;</p>
<ul>
<li>List item 1</li>
<li></li>
<li>List item 3</li>
</ul>
</div><!-- .entry-content .clear -->
```
