### ISSUE TITLE
PHP Errors: Unknown modifier

### ISSUE THREAD

**Issue by reekes** [TaxoPress/TaxoPress#1962]
I find these errors in the PHP_errorlog

```
Warning: preg_match(): Unknown modifier 'R' in /home/customer/www/my.domain/public_html/wp-content/plugins/taxopress-pro/inc/class.client.autoterms.php on line 567

Warning: preg_match(): Unknown modifier 'I' in /home/customer/www/my.domain/public_html/wp-content/plugins/taxopress-pro/inc/class.client.autoterms.php on line 567

```

## Expected Behavior

no errors in PHP_errorlog

## Current Behavior

errors 

## Possible Solution

unknown

## Steps to Reproduce (for bugs)

I've installed Taxopress

## Your Environment

I do not use AI integration (frankly, I don't understand why I would)

Taxopress version 3.11.1
WordPress 6.4.2
PHP version 8.1.26
hosted at SiteGround

**Comment by reekes** [comment]
Really @ojopaul you closed this issue without a response...after I filed it over a month ago...and didn't wait one day for a response?

**Comment by reekes** [comment]
I take this as meaning Taxopress doesn't care about customer reported problems

**Comment by reekes** [comment]
@stevejburge is this your new guy to close bugs without fixing them?

**Comment by ojopaul** [comment]
@reekes I didn't manually close the issue without fixing it. The reason the issue was closed as completed is because I raised a pull request that fixed the issue and tag this issue number on it yesterday.

In that case, github will close the issue as completed since the PR is merged and that's the workflow we follow to give us a cleaner view of what we're working on, what we've done and what remain in current milestone.

I'm sure there's no way for you to receive the fixes if we haven't make a release to the plugin yet which is done after all milestone issues are fixed or completed.

If you check plugin page, you'll see we haven't make any release since you reported the issue.

I can provide you a testing package if you want to test before we make official release to confirm if it works for you.

**Comment by reekes** [comment]
Got it, thanks.

It's not clear to me, your customer, what your process is or how you're using GitLab. There's nothing in this thread that gives me a hint that this issue was fixed. I also do not see anything that would tell me to expect a fix. About all I can see is the item was closed.

I reported the problem to support months ago. I was told it was best to file a bug in GitHub. Not a "user friendly" type of way to report bugs. So since this is an official support area I was expecting something more than what I can find in this thread.

**Comment by stevejburge** [comment]
Hi @reekes. 

Github is basically a way that developers can interact with our plugins. I don't believe we asked you to open a ticket here. If we did, it was a mistake and I apologize. 

Yes, Github is not "user friendly". We don't use Github for customer support or communication. That's all done via our official website. Most companies will keep their Github repos private. We just make them open in case it's useful to someone.

@ojopaul is one of our very best developers and has been with us for years.
