### ISSUE TITLE
Add Custom Prompts to OpenAI settings

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#1978]
We could allow users to enter their own prompts, as with PublishPress Checklists

Some ideas here: https://promptperfect.jina.ai/

**Comment by ojopaul** [comment]
@stevejburge This is a good choice but I'll like to put a disclaimer to you before implementing this. Checklists requirement is not same thing as TaxoPress tags suggestion. Most of the time, if Prompt is not carefully tailored towards providing result in tags format, it won't work as OpenAI will produce sentences or paragraphs and no way for us to format it.

For example, here's the default prompt and the reason tags is mentioned twice, in the content and ended with Tags: is to make sure OpenAI return tags like Apple, Banana, Cake etc instead of what it's used to which is sentences or paragraph.

`Extract tags from the following content: '{content}. Tags:'.`

I'll add this settings but we have no control over the result format for those that'll be using it if they couldn't put a prompt that instruct OpenAI to return tags format.

**Comment by ojopaul** [comment]
Closing this for https://github.com/TaxoPress/TaxoPress/issues/1948#issuecomment-1991772513
