### ISSUE TITLE
Small text improvements for the TaxoPress AI screen

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2059]
We use "View Terms" for all these buttons. I think we could be clearer on each one.

For example, we don't need this button:
![Screenshot 2024-07-02 at 10 43 13 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/fe1bd456-93f7-4456-bbe5-0e5bd9c17ae5)

This could be "View Current Post Terms"
![Screenshot 2024-07-02 at 10 45 49 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/47345a1a-5e3e-4f8b-9de9-7f75009438a1)

This could be "View Suggested Terms"
![Screenshot 2024-07-02 at 10 46 35 AM](https://github.com/TaxoPress/TaxoPress/assets/3868028/bcdb068c-898b-4ff2-8d7e-14005e1c41fe)

**Comment by ojopaul** [comment]
1. I think we still need the button because you can change post type and post and when you do, the button is needed for newly selected post
![button](https://github.com/TaxoPress/TaxoPress/assets/92122385/ed30081b-a032-47cd-8631-0fc149f9fb92)
2. According to your screenshot:
- Manage Post Terms => View Current Post Terms
- Suggest Existing Terms => View Suggested Terms

So, the remaining button should remain "View Terms" or View Existing Terms, View OpenAI terms etc? @stevejburge

**Comment by stevejburge** [comment]
Yes, we keep the button but just change the text on the button

**Comment by ojopaul** [comment]
@stevejburge You didn't answer my second question

**Comment by stevejburge** [comment]
Yes to the second question. Thats correct
