### ISSUE TITLE
Update the dashboard to cover the new features

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2147]
![Screenshot 2024-08-19 at 1 04 23 PM](https://github.com/user-attachments/assets/42838fe9-0954-4cff-bbf8-31a41710079a)

**Comment by ojopaul** [comment]
@stevejburge Can you be specific with these new features?

The only thing I could recollect is Auto Term Existing Content which is dependent on Auto Term itself and been controlled if Auto Term is enabled or disabled.

**Comment by stevejburge** [comment]
Yes, Auto Terms is one. For example, you can't disable "Existing Content" or "Metaboxes"
![Screenshot 2024-08-20 at 10 21 33 AM](https://github.com/user-attachments/assets/76d48280-8641-4ab9-8a9f-b26f7bc8bde8)

**Comment by stevejburge** [comment]
Thanks. So if "Auto Terms" is disabled, maybe "Existing Content" or "Metaboxes" are disabled also?

**Comment by ojopaul** [comment]
@stevejburge Is Existing Content menu currently showing when Auto Terms is disabled?

**Comment by stevejburge** [comment]
Yes, it does:
![Screenshot 2024-08-20 at 11 02 57 AM](https://github.com/user-attachments/assets/6b9a29a0-86db-4547-8ebd-f513c87100bc)

**Comment by ojopaul** [comment]
Even when not on TaxoPress dashboard?

If so, can we update the issue to the path we're taking for future reference?

If we're removing specific menu when another is not enabled, adding another settings that only work when another is disabled etc.

Having issue that show what we're working on make it easy to reference back later when we're looking for reason something is working in a specific way instead of starting a new conversation when we could have forgotten why.

**Comment by stevejburge** [comment]
OK, fair point. Let's come back and make a decision for this one when it's time for the next TaxoPress release
