### ISSUE TITLE
Text change for Related Posts option

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2341]
- Enter the text that should be displayed before the posts list. 
- Enter the text that should be displayed after posts list. 
![Screenshot 2024-11-07 at 9 52 21 AM](https://github.com/user-attachments/assets/ccf2691d-10e6-4d4a-a7dc-15fbe8a130a5)

**Comment by lattaai3** [comment]
Hello, I tried to fix the issue

This is what I did:

Add two new text input fields in the 'General' tab for entering text to display before and after the related posts list.

I also created pull request: https://github.com/TaxoPress/TaxoPress/pull/2342


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.
