### ISSUE TITLE
Preview feature is not respecting "Auto Terms Limit"

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2346]
Using the Preview feature, it's not respecting "Auto Terms Limit". This is an example with "3" set for the limit. I'm only using the "Existing Terms" option

![Screenshot 2024-11-07 at 12 38 15 PM](https://github.com/user-attachments/assets/d04bba9e-85c6-4bb6-a8de-150b192a3bd7)

**Comment by stevejburge** [comment]
I think we can see the same problem in "Existing Content" too
![Screenshot 2024-11-07 at 12 38 55 PM](https://github.com/user-attachments/assets/9b1ee66f-dcba-4c2d-a190-5d0c9a0c1cef)

**Comment by ojopaul** [comment]
@stevejburge since merging TaxoPress AI with Auto Terms, maybe we should set some things straight.

The Auto Term limit and most of the auto terms settings is for when creating or updating posts.

Instead of having different issues on stuffs like this, can we have an issue on what settings should apply to Metabox, Existing Content especially in relation to all the sources including OpenAI and others?

**Comment by ojopaul** [comment]
@stevejburge How do you think we apply this settings to OpenAI response? What exactly is the purpose of asking OpenAI for tags if we remove them cos they're not whole word or because they have hash tag in front of them and end up seeing response message of  "no tags found". 

![t](https://github.com/user-attachments/assets/b52b74cd-f8cb-4bb1-800b-d958feab5d00)

**Comment by stevejburge** [comment]
OK, thanks. I think this issue may be very helpful in clearing up confusion.

In this case, I guess these settings have to move? If a setting is unique to a source or output, it should be moved there?

For example, "Hashtags" should be here?
![Screenshot 2024-11-07 at 1 15 18 PM](https://github.com/user-attachments/assets/8e06c8d5-bb3c-47ea-9275-9ead25de0b41)
