### ISSUE TITLE
Clean up the "Manage Terms" page

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/taxopress#248]
This page can get very messy and hard to read. The tag cloud especially:
<img width="1425" alt="Screen Shot 2021-03-03 at 2 12 49 PM" src="https://user-images.githubusercontent.com/3868028/109859211-b3af1a80-7c2a-11eb-8503-b9db8bffd852.png">

Let's make two changes:

1. Move to a Tabbed Display
2. Move from a cloud to the table layout used at /edit-tags.php?taxonomy=category. We can remove the Description and Slug columns if there's not enough space

![manage-terms](https://user-images.githubusercontent.com/3868028/109860216-ddb50c80-7c2b-11eb-97f8-93ef540a8b3f.jpg)

**Comment by Vidyut** [comment]
For the tag cloud - I have never used it. I have too many tags for it to be useful and I know the tags starting with "A" very well. lol. The sorting is not very useful in practical terms. Maybe if there aren't a lot of tags. 

Some possibilities / suggestions:

1. The tag cloud could be made optional.
2. The selector could have an option for searching one or more terms - the autocomplete in the text fields already does this.
3. To really awesome-max the tag cloud, the searching could have selectors to keep the terms checked pinned to the top of the cloud while other sorting or searching is done.
4. The default tag cloud could have a sane cutoff for listed terms and some pagination instead, so that there is a way to see all the terms systematically. At least for the most-least used and A-Z, Z-A. Pagination for random probably won't mean much, unless it is by term ID or something - then it would basically show terms in the order they were created on the blog.

**Comment by stevejburge** [comment]
Thanks @Vidyut 

The proposal here is to remove the cloud entirely and replace it with a sortable table
