### ISSUE TITLE
footer is broken on taxonomy edit screens

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#381]
<img width="1277" alt="Screen Shot 2021-04-15 at 9 58 23 AM" src="https://user-images.githubusercontent.com/3868028/114881623-2afecf00-9dd1-11eb-8348-ca7ec36ee119.png">

**Comment by olatechpro** [comment]
I don't understand what you mean by the footer is broken. If it's because of it not been by the bottom, it's the way the copyright is added which is immediately after the page content and the reason why it's that way is because the content on that page is not long like other pages. here's what i have here.

<img width="1440" alt="Screenshot 2021-04-19 at 4 51 42 AM" src="https://user-images.githubusercontent.com/46832636/115179435-356be200-a0cb-11eb-92de-bf0239644adc.png">

**Comment by stevejburge** [comment]
@olatechpro OK, let's skip this for now

**Comment by olatechpro** [comment]
Closing in favour of #712
