### ISSUE TITLE
Tag link format box

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#478]
Let's make this box much wider.

The documentation link also needs to change:
https://taxopress.com/docs/format-tag-clouds/   (I need to fill this in before launch)

<img width="701" alt="Screen Shot 2021-05-26 at 7 47 06 AM" src="https://user-images.githubusercontent.com/3868028/119670983-9b4c3780-bdf6-11eb-9193-419495d34f33.png">

**Comment by olatechpro** [comment]
Firstly, it look odd longer than others and secondly, it still doesn't contain the whole content.

So, our best option is textarea and will be updating that instead unless you want otherwise:

<img width="1440" alt="Screenshot 2021-05-26 at 4 47 59 PM" src="https://user-images.githubusercontent.com/46832636/119691184-46cea980-be42-11eb-8d92-347eef223d53.png">

**Comment by olatechpro** [comment]
Here's the textarea look. It may be confusive though.
So, let me know which you feel we should opt for ?

<img width="1440" alt="Screenshot 2021-05-26 at 4 52 07 PM" src="https://user-images.githubusercontent.com/46832636/119691734-bb094d00-be42-11eb-80bb-024028ec04c9.png">

**Comment by stevejburge** [comment]
Let's go with your first screenshot, please
