### ISSUE TITLE
The post does not display the updated taxonomy name.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#527]
1. Add New taxonomy by giving valid entries (plural label-tests1)
 2. Select Post type -> Posts
 3. Edit the taxonomy name just created (tests1 to testsone) and save
 4. Create a post
 5. Look for the taxonomy name in the post

The Post should display the updated taxonomy name(testsone). But the post displays the old taxonomy name that is created before updating.

![taxonomy in post](https://user-images.githubusercontent.com/83974581/120705082-346cf500-c46c-11eb-8608-1c9503976940.JPG)
![taxonomy name](https://user-images.githubusercontent.com/83974581/120705085-35058b80-c46c-11eb-8a7f-d4e6a2f2326a.JPG)

**Comment by olatechpro** [comment]
Hi @sathyapriya91 and @stevejburge , this is not our bug or can be otherwise term wordpress bug, unlike the previous classic editor, gutenberg uses 'Menu Name' to list taxonomies as shown in this screenshot instead of singular or plural name.

<img width="1141" alt="my-new-tag" src="https://user-images.githubusercontent.com/46832636/120994422-5e7c2b00-c77c-11eb-8df3-51f0dbb13dae.png">

**Comment by stevejburge** [comment]
@olatechpro Interesting, thanks. We'll document that Gutenberg issue
