### ISSUE TITLE
Can't add term to all posts by selecting the term in 'Manage terms'

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#544]
1. Go to 'Manage Terms'
2. Select 'Posts', 'tags' -> Change selection
3. Have few tags with 'Count'- 0
4. Select Add Terms -> Add Terms to all posts
5. Select any tag from the left with count 0 -> Click 'Add' button

Term should be added to all the posts and count should be displayed.

Type the same term instead of selecting from the left, and click 'Add Term' button. The term is added and count is displayed.

![selecting from left](https://user-images.githubusercontent.com/83974581/121738278-de710080-caae-11eb-94d0-45a95229e944.JPG)
![type and search](https://user-images.githubusercontent.com/83974581/121738283-df099700-caae-11eb-9402-751c05f76dea.JPG)

**Comment by stevejburge** [comment]
@sathyapriya91 Thanks. I can confirm this.

Click a term in the left box, and it is added to every box:


![Screen Shot 2021-06-14 at 11 23 17 AM](https://user-images.githubusercontent.com/3868028/121917252-f214a500-cd02-11eb-859b-335f1d96d85b.png)
![Screen Shot 2021-06-14 at 11 23 20 AM](https://user-images.githubusercontent.com/3868028/121917253-f2ad3b80-cd02-11eb-9346-a0737125978e.png)
![Screen Shot 2021-06-14 at 11 23 23 AM](https://user-images.githubusercontent.com/3868028/121917254-f2ad3b80-cd02-11eb-82c4-d4605b89136f.png)

**Comment by olatechpro** [comment]
Hi @stevejburge , that's not the issue explained by @sathyapriya91 .

The issue is terms are not been added when using 'Add terms to all post' selecting from the term list.

Now, back to your new message, it doesn't have effect on what happen and the reason for adding all clicked tags to all tab box is to allow easy navigation and action without the need to be clicking again when switching tabs but if you want it to be added to only active tab box and of course, disappear when user switch tab, then that can be updated as well.
