### ISSUE TITLE
Deactivated taxonomy  is displayed in admin menu.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#573]
1. Create a taxonomy and Deactivate it
2. Save Taxonomy
3. Place the cursor on Posts/Pages

Deactivated taxonomy name should not be displayed

Click on the posts/pages. De activated taxonomy name is not shown.

Click on the 'TaxoPress' and place the cursor on posts/pages. De activated taxonomy name is shown.

![Tax](https://user-images.githubusercontent.com/83974581/122102139-f788f280-cdc9-11eb-9b45-793d9d7773fc.JPG)

**Comment by olatechpro** [comment]
@sathyapriya91, is deactivated menu displayed on any other pages aside the taxopress settings page?

**Comment by sathyapriya91** [comment]
@olatechpro  
No, Deactivated taxonomy is displayed only when taxopress page is selected. 'Invalid taxonomy' page is shown while selecting the deactivated taxonomy from Taxopress page.

**Comment by olatechpro** [comment]
@sathyapriya91 and @stevejburge, we need to display all taxonomy on that page either deactivated or not and for that reason, exclusion is made because implementing the deactivation on that settings page means we won't be able to show it in the list since practically, it's not existing and no way we can access it from WordPress existing taxonomy list.

In a more explanatory note, deactivated taxonomy means it shouldn't be accessible or displayed on any pages and which shows no way for us to list it on taxopress taxonomy page as well and for that reason, we had to exclude taxonomy settings page from implementation and following the link from that page will definitely result in error page and neither is it listed on any other pages. 

It's not a bug but how it's suppose to work.

**Comment by stevejburge** [comment]
thanks @olatechpro 

@sathyapriya91 thanks for your thorough testing
