### ISSUE TITLE
Tags in the post are auto linked even if "Auto link all tags" is unchecked.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#633]
1. In Taxonomy -> Settings -> Select "Auto links tags" check box
2. In "Auto link" tab, uncheck "Auto link all tags" and save
3. Create a post and add new tag that is not included in post tags
4. Publish the post and check the auto link

The new tag added in the post should not be auto linked as the Auto link all tags is unchecked.

![alltags](https://user-images.githubusercontent.com/83974581/125131749-1a03e800-e0b8-11eb-99fa-268b67350c0c.JPG)
![auto link all tags](https://user-images.githubusercontent.com/83974581/125131753-1a9c7e80-e0b8-11eb-85f6-755967a7b04a.JPG)
![post](https://user-images.githubusercontent.com/83974581/125131755-1a9c7e80-e0b8-11eb-9b2e-c863919cc318.JPG)

**Comment by anhredweb** [comment]
@stevejburge I think there's some misunderstand about the bug as what we met and will be described bellow:
1. I unchecked the option and click `Update options` for ensure the settings saved. 
![image](https://user-images.githubusercontent.com/6948022/126951469-1a6daaf5-2ba2-409c-9d6b-80f52e05a3eb.png)

2. Then we go to `Manage Terms` and check the list terms before make a new post: 
![image](https://user-images.githubusercontent.com/6948022/126952557-c14b3c8f-2331-492f-8dc2-fd326c7fc5c9.png)

3. Create a new post with tag is `tag`, which is not include at the list of step 2:
![image](https://user-images.githubusercontent.com/6948022/126953138-0f65ac88-1c09-4a86-9967-0a87b5e59973.png)

Then you see the post, `tag` is linked because it's auto created at the list terms and it's a tag of the post 
![image](https://user-images.githubusercontent.com/6948022/126953435-2aa5cd5b-f39d-4600-8925-c34ac8f7e307.png)

4. Now we update the post with `Test` is existed before and not in post tags and it isn't linked as logic. 
![image](https://user-images.githubusercontent.com/6948022/126954523-85447b9d-ca3b-4b5f-a311-c0c9694986b4.png)

So we think the function is correct and not the bug. Is it right @stevejburge

**Comment by stevejburge** [comment]
@anhredweb I think the solution may be a new description and label.

![Screen Shot 2021-07-26 at 10 49 12 AM](https://user-images.githubusercontent.com/3868028/127009487-b20f4583-e70d-4a5b-b7e7-76491d79e23a.png)

Old: 

> Auto link all tags ? | If checked, tags found in post will be auto linked even if not included in post tags.

New:
"Add links for unattached terms"
"By default, TaxoPress will only add Auto Links for terms that are attached to the post. If this box is checked, TaxoPress will add links for all terms".

**Comment by anhredweb** [comment]
Hi @stevejburge 

I push MR: https://github.com/TaxoPress/TaxoPress/pull/704 to update text

Thanks.
