### ISSUE TITLE
Manage Terms - Taxonomy not appearing in selection list

### ISSUE THREAD

**Issue by Bachynski** [TaxoPress/TaxoPress#651]
While testing the compatibility of TaxoPress and WooCommerce. When initially changing post type from "Posts" to "Products" a message stating "You are viewing the taxonomy 'Product type' appears, however it cannot be found in the taxonomy drop down list.

1. Click 'TaxoPress' tab
2. Click on 'Manage Terms' sub tab
3. Click on the drop down menu that says 'Posts' and replace it with "products
4. Click the 'Change Selection' button and observe the brown message "You currently use the custom post type :Products" and the taxonomy "Product Type"
5. Click taxonomy drop down list
6. Observe no taxonomy by the name "Product Type"

One would expect that even if the default view is "Product Type" it would still appear in the selection list.

![Taxonomy 'Product Type' does not appear](https://user-images.githubusercontent.com/79052272/125361090-11b2e380-e32a-11eb-92cc-d1add0968633.png)

 - OS: Windows 10
 - Browser Chrome
 - Version 91.0.4472.114

**Might be related to Issue #650

**Comment by olatechpro** [comment]
The reason product type is not available for selection is because the applicable checkbox in the admin menu settings fro taxonomy is not checked/enabled.

<img width="1440" alt="Screenshot 2021-07-13 at 9 23 35 AM" src="https://user-images.githubusercontent.com/46832636/125418022-d9c362d3-2010-4057-9bfc-6801d44463fc.png">
