### ISSUE TITLE
Couldn't  save the related posts 'Title header' with 'None'.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#697]
1. Select Taxopress -> Related Posts
2. Edit the Related post
3. In Title header -> Select 'None'
4. Save related posts and observe

Related post title header should be saved with the selected 'None'. 

Related posts Title header displays H4 after selecting None and saving.
![title header](https://user-images.githubusercontent.com/83974581/126231047-c7ec1414-e1de-4d2d-888f-2b79dbd0e155.JPG)

**Comment by stevejburge** [comment]
@sathyapriya91 Thanks. Do you think this is a bug? Can users do the same thing with "Hide title in output?"

**Comment by olatechpro** [comment]
Hi @stevejburge, I've checked the issue and it's same as this #542

The problem is, when user select none as title header from drop down, the value is empty and as a result show default as selected(Note, it doesn't affect application but the edit screen alone as no value revert to default value) 

You can move to the appropriate/next milestone so it can be fixed.

**Comment by stevejburge** [comment]
Thanks @olatechpro and @sathyapriya91
