### ISSUE TITLE
Use new engine

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#716]
Do you think we should enable this option by default?

![Screen Shot 2021-08-03 at 10 12 43 AM](https://user-images.githubusercontent.com/3868028/128030602-8926b1df-47e7-42d2-95c2-cfb0fdc10194.png)

**Comment by olatechpro** [comment]
Even though it's the fastest and most optimized method we can not enable it by default as it's possible some host may not enable the PHP Dom requirement unless user enable them manually.

So, instead, this is what i did, i first check if the class needed for new engine is enable on the client host and if so, I make use of new engine (as it's the most efficient and fastest) irrespective of what user select since we're after best result and I believe that filled in the gap of It been enable by default but if not available, go with user option. 

@stevejburge

**Comment by stevejburge** [comment]
OK, let's change the text then:

"This new Auto Links engine uses the DOMDocument PHP class and may offer better performance. If your server does not support this functionality, TaxoPress will use the usual engine."

**Comment by olatechpro** [comment]
Okay, so, we should make it default and change the label after?
@stevejburge

**Comment by stevejburge** [comment]
@olatechpro Yes, if it's better, let's make if the default

We can disable it if DOMDocument PHP isn't available
