### ISSUE TITLE
Post displays overlapped texts when large texts are entered in plural label.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#745]
1. Select Taxopress -> Taxonomies
2. In Plural label enter a large text without any spaces in it (thisisaplurallabelsnotasingularlabel.thisisaplurallabelnotasingularlabel..thisisaplurallabelnotasingularlabel.thisisaplurallabelsnotasingularlabel.)
3. Enter singular label, Select any post types and select Add Taxonomy
4. Create a post and observe the added taxonomy

The created taxonomy does not look pleasant as it is overlapped on the text. 

As there is no limit in entering the text, user might enter large text.

![plual1](https://user-images.githubusercontent.com/83974581/128418935-8fc71455-69cd-4fec-8f17-56b49547eb29.JPG)
![plural](https://user-images.githubusercontent.com/83974581/128418938-2d54bd99-1365-4f5c-a835-2a43aca7a23a.JPG)

**Comment by olatechpro** [comment]
I limit the character to 100 for the input but this may not solve what the issue posted here as it's a rendering issue(WordPress render taxonomy meta field not TaxoPress) and we should be careful of trying to limit the input characters too low since we don't know the use case of every site and of course, the test case here is unrealistic as well as maybe WordPress break word and i this case, it's a very long word(which is not realistic). So, decided to limit the field to 100 character and if for any reason, the limit affect any user usecase, then we may find a reasonable limit
