### ISSUE TITLE
Options box

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#844]
Posts with terms already added - Only use Auto Terms on posts with no added terms.
Whole words - Only add terms when the word is an exact match. Do not make matches for partial words.
Hashtags - Enabling this feature will disable auto terms for any words with a # prefix.

Note: the "hashtags" row should only appear if "Whole words" is checked

<img width="932" alt="Screen Shot 2021-09-13 at 1 13 04 PM" src="https://user-images.githubusercontent.com/3868028/133127572-a0b8f093-31f6-4fd4-a1c7-c325ca6afd59.png">

**Comment by olatechpro** [comment]
@stevejburge, this label and description is confusing.

> Posts with terms already added - Only use Auto Terms on posts with no added terms.

'Post with or without term is auto term when the option is not checked.

So, putting the label as 'Post with terms already added' leaves impression of auto term only working for post that have terms already and not both since the description reads 'Only use Auto Terms on posts with no added terms.'

**Comment by stevejburge** [comment]
good catch @olatechpro 

OK, let's use "Target content" as the label

**Comment by olatechpro** [comment]
The description of hashtag is not correct as well

> Enabling this feature will disable auto terms for any words with a # prefix.

Primarily, words with # in-front of them doesn't work when whole word is selected as # is not considered part of words.

So, this feature enable the support for # to count as a word.

E.g, #year will be auto tagged if '#year' exist in term list which wouldn't have had it been the support for hashtag is not enabled.

So, saying enabling the option will will disable auto terms for any words with a # prefix doesn't seems to be correct order than explain enabling it enable support for #hashtag

@stevejburge

**Comment by olatechpro** [comment]
Also, the support for hashtag works in both settings either whole word is checked or not, the reason the fix is highlighted in current description is because it's glaring when whole word is selected and then '#football' fail to be tagged even when term '#football' exist.

For when whole word is not checked 'football' from #football will be tagged if 'football' exist and also, '#football' will be tagged if '#football' exist.

So, no reason to hide it if whole word is checked or not

@stevejburge

**Comment by stevejburge** [comment]
@olatechpro OK, I'm a little confused :)

Should the label be "Support hashtags symbols # in Auto Terms"?

**Comment by olatechpro** [comment]
Sorry about the confusion, the auto term feature is kind of wide.

And yes, it should be support hashtags and no need to hide it

**Comment by stevejburge** [comment]
Awesome, let's do that
